### ISSUE TITLE
Download media shared via messages

### ISSUE THREAD

**Issue by DigitalUser10k** [k0rnh0li0/onlyfans-dl#16] opened 2021-01-21 09:21 UTC
Sometime creators share links via messages (after e.g.: giving a tip).

It seems these are currently not being downloaded. Would it be possible to add this feature?
Hopefully messages are accessible via current APIs & authtoken, i.e.: nothing extra is required other than scanning messages for media?

**Comment by MakotoYasuhiro** [comment] 2021-01-21 21:01
Turns out I ended up getting bored and doing this.

https://github.com/MakotoYasuhiro/onlyfans-dl

You can now choose to download posts, archived posts, stories, highlights, messages, and paid content.

You can choose which you want to download by finding the block of "DOWNLOADING_{content type}" and setting values to True or False. Let me know if you have any questions or issues.

**Comment by Chazy12** [comment] 2021-01-21 22:43
> Turns out I ended up getting bored and doing this.
> 
> https://github.com/MakotoYasuhiro/onlyfans-dl
> 
> You can now choose to download posts, archived posts, stories, highlights, messages, and paid content.
> 
> You can choose which you want to download by finding the block of "DOWNLOADING_{content type}" and setting values to True or False. These are all **True** by default.
> 
> You can also choose whether you want to use sub-folders (like /profiles/{user}/archived/photos) or just have everything download to /profiles/{user}/photos. Sub-folders are currently enabled by default.
> 
> Let me know if you have any questions or issues.

gave me a subfolder error syntax.
![2021-01-21_233319](https://user-images.githubusercontent.com/6653347/105421493-78402a00-5c42-11eb-9ed7-20e3b2cdd715.jpg)

**Comment by MakotoYasuhiro** [comment] 2021-01-21 22:56
> gave me a subfolder error syntax.
Make sure you download the latest one. Looks like you grabbed the middle one of my last three commits

**Comment by Chazy12** [comment] 2021-01-21 23:11
> > gave me a subfolder error syntax.
> > Make sure you download the latest one. Looks like you grabbed the middle one of my last three commits

cloned latest version.

**Comment by MakotoYasuhiro** [comment] 2021-01-21 23:20
> cloned latest version.

The fix for that was committed 2 hours ago https://github.com/MakotoYasuhiro/onlyfans-dl/commit/c5455cb282cf2ac0f3898ade35560b1b80fe7132.

It's just a single missing ':' at the end of the line.

**Comment by DigitalUser10k** [comment] 2021-01-21 23:32
Thanks, this seems to generally work for me. Just one question:

Any reason why you are setting `MESSAGE_LIMIT = "10"` ?

That limit is set to 100 for all other categories. In my case it resulted in one media not being initially downloaded (fixed by setting  `MESSAGE_LIMIT = "100"`.

Other than that it works perfectly! And I find the variable to flatten the directory structure via the `USE_SUB_FOLDERS` variable very handy :-)

**Comment by MakotoYasuhiro** [comment] 2021-01-21 23:39
> Thanks, this seems to generally work for me. Just one question:
> 
> Any reason why you are setting `MESSAGE_LIMIT = "10"` ?
> 
> That limit is set to 100 for all other categories. In my case it resulted in one media not being initially downloaded (fixed by setting `MESSAGE_LIMIT = "100"`.
> 
> Other than that it works perfectly! And I find the variable to flatten the directory structure via the `USE_SUB_FOLDERS` variable very handy :-)

Thanks!

And that's strange, for me MESSAGE_LIMIT 100 didn't work and threw errors, but a limit of 10 worked fine. That then lead to me switching things over to using the variables they now use, as I was unsure if it'd be different limits depending on the content type. 100 ended up working for all of them other than messages for me.

I may move those limits up to the configuration area to make them more visible to people. Give all a default of 100 with notes on what to change in-case anyone gets an error like I was getting.

**Comment by Chazy12** [comment] 2021-01-26 23:27
> > Thanks, this seems to generally work for me. Just one question:
> > Any reason why you are setting `MESSAGE_LIMIT = "10"` ?
> > That limit is set to 100 for all other categories. In my case it resulted in one media not being initially downloaded (fixed by setting `MESSAGE_LIMIT = "100"`.
> > Other than that it works perfectly! And I find the variable to flatten the directory structure via the `USE_SUB_FOLDERS` variable very handy :-)
> 
> Thanks!
> 
> And that's strange, for me MESSAGE_LIMIT 100 didn't work and threw errors, but a limit of 10 worked fine. That then lead to me switching things over to using the variables they now use, as I was unsure if it'd be different limits depending on the content type. 100 ended up working for all of them other than messages for me.
> 
> I may move those limits up to the configuration area to make them more visible to people. Give all a default of 100 with notes on what to change in-case anyone gets an error like I was getting.
> 
> I inadvertently ended up finding that option of setting it to 10 from this commit in another fork [50f4285](https://github.com/k0rnh0li0/onlyfans-dl/commit/50f428553c5159d2081a7b88295fcbf2d1895090). My paid content was downloading fine at 100, not sure why he needed his at 10. But my messages weren't downloading at 100, so I decided to try 10 like that guy had done, and it ended up working for me.

seems of changend something..
i'm stuck on "finding posts.."

**Comment by thomasthespider** [comment] 2021-02-09 23:18
I've updated this script to implement the fixes from the main script so that it works again

[onlyfans-dl-messages.zip](https://github.com/k0rnh0li0/onlyfans-dl/files/5954823/onlyfans-dl-messages.zip)

**Comment by bnsave100** [comment] 2021-03-29 15:21
> 
> 
> I've updated this script to implement the fixes from the main script so that it works again
> 
> [onlyfans-dl-messages.zip](https://github.com/k0rnh0li0/onlyfans-dl/files/5954823/onlyfans-dl-messages.zip)

this will download pics + vids + msgs in one go right ?

**Comment by neuri4848** [comment] 2021-04-11 10:36
> I've updated this script to implement the fixes from the main script so that it works again
> 
> [onlyfans-dl-messages.zip](https://github.com/k0rnh0li0/onlyfans-dl/files/5954823/onlyfans-dl-messages.zip)

this just logs me out. anything specific i need to do?

**Comment by dodecaphone** [comment] 2021-04-24 00:30
> 
> 
> > I've updated this script to implement the fixes from the main script so that it works again
> > [onlyfans-dl-messages.zip](https://github.com/k0rnh0li0/onlyfans-dl/files/5954823/onlyfans-dl-messages.zip)
> 
> this just logs me out. anything specific i need to do?

Has this issue been fixed?

**Comment by Rit76Horizon** [comment] 2021-04-24 01:06
> Turns out I ended up getting bored and doing this.
> 
> https://github.com/MakotoYasuhiro/onlyfans-dl
> 
> You can now choose to download posts, archived posts, stories, highlights, messages, and paid content.
> 
> You can choose which you want to download by finding the block of "DOWNLOADING_{content type}" and setting values to True or False. These are all **True** by default.
> 
> You can also choose whether you want to use sub-folders (like /profiles/{user}/archived/photos) or just have everything download to /profiles/{user}/photos. Sub-folders are currently enabled by default.
> 
> Let me know if you have any questions or issues.

Sorry if I'm being a bother, I'm new to basically all of this. but I can't actually figure out "what" I need to do to be able to use this. I know it might be a stupid question but I find the instructions to be completely unclear, and I'm asking you since you made what appears to be a fork that is just overall better (IE supports messages and archived)

I downloaded the newest version of Python as I assumed I would need that, got my User Agent where I was shown and got my access token, All fairly easy things I had assumed, but then I get to actually using it and I can't figure it out at all. Trying to use the CMD just results in the README popping up over and over again and I haven't the slightest idea what I need to be putting into Python to use that route either. 

I tried to figure things out on my own looking at what I needed to be doing from the issue requests but I got nothing, so as a last resort I'm asking someone directly for help, as my only even remotely comparable experience is using Youtube-dl.

Once again I apologize if I'm bothering you but it is what it is I guess.

**Comment by BenSomner** [comment] 2021-04-28 12:42
> > > I've updated this script to implement the fixes from the main script so that it works again
> > > [onlyfans-dl-messages.zip](https://github.com/k0rnh0li0/onlyfans-dl/files/5954823/onlyfans-dl-messages.zip)
> > 
> > 
> > this just logs me out. anything specific i need to do?
> 
> Has this issue been fixed?

Seems the issue is still present in this version as I'm seeing the same thing. Starts by "Getting user auth info..." then returns "ERROR: User not found" then refreshing the web page I'm logged out of my account.

**Closed** 2024-01-06 02:34 UTC
