### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by xico19** [k0rnh0li0/onlyfans-dl#33] opened 2021-02-10 01:36 UTC
im getting this error
![image](https://user-images.githubusercontent.com/78832630/107452048-70d4b800-6b40-11eb-8037-223ef9f70c67.png)

**Comment by k0rnh0li0** [comment] 2021-02-10 01:40
Duplicate of #29 , #28, and #25.

**Closed by k0rnh0li0** 2021-02-10 01:40 UTC
