### ISSUE TITLE
Keep getting Error: Please refresh the page

### ISSUE THREAD

**Issue by SenpaiX00** [k0rnh0li0/onlyfans-dl#94] opened 2021-04-30 21:15 UTC
Not sure why this is happening. I have checked to make sure I am not logged in from multiple places. Agent is correct. Any help would be appreciated.

**Comment by cdevoss** [comment] 2021-04-30 23:04
Yeah it's broken for me as well.

Looks like all the API calls to api2/v2 require "time" and "sign" headers and if they are not set correctly you get a 401 "please refresh the page". I was ablr to prove this out with curl calls to api2/v2/profile/me.

time header looks like unix epoch time in milliseconds.
I'm assuming sign header is some api request signature but I haven't look at how it is set/generated.

**Comment by SlickPW** [comment] 2021-04-30 23:06
Yeah, just to confirm, it's not working for me either anymore.

**Comment by SenpaiX00** [comment] 2021-04-30 23:31
> Yeah it's broken for me as well.
> 
> Looks like all the API calls to api2/v2 require "time" and "sign" headers and if they are not set correctly you get a 401 "please refresh the page". I was able to prove this out with curl calls to api2/v2/profile/me.
> 
> time header looks like unix epoch time in milliseconds.
> I'm assuming sign header is some api request signature but I haven't looked at how it is set/generated.

This is interesting. If you get any info on how it's generated, would be interesting. 

Whatever the change is, it's happened today.

**Comment by Amenly** [comment] 2021-05-01 01:06
> 
> 
> Yeah it's broken for me as well.
> 
> Looks like all the API calls to api2/v2 require "time" and "sign" headers and if they are not set correctly you get a 401 "please refresh the page". I was able to prove this out with curl calls to api2/v2/profile/me.
> 
> time header looks like unix epoch time in milliseconds.
> I'm assuming sign header is some api request signature but I haven't looked at how it is set/generated.

The `sign` portion looks like it contains a SHA-1 hash in the form of a hexadecimal digest in the middle. Not sure how it's generated but it seems DC figured out it's in the javascript. The first value and the last hex value with 6 symbols in the `sign` header seem to always be constant. Another thing I can't figure out is where the hex value with 3 symbols after the hash comes from. That one seems to always be different like the hash value.

**Comment by ProjektPremium** [comment] 2021-05-01 01:51
> 
> 
> Yeah, just to confirm, it's not working for me either anymore.
> Also, I don't know if this is connected but now when I go to the OF site in the desktop Firefox browser, on the OF loading screen, I get the message: "Just a moment... We'll try your destination again in 15 seconds" with a scroll bar across the bottom and after a few moments it goes to the site proper. Never had that before.

The site has had the on and off for a while but it never affected any scraping software. I have developed my own and when other scrapers are down mine usually still works. Mine has also been stopped in it's tracks.

**Comment by dengrove** [comment] 2021-05-01 06:16
is it really fix?

**Comment by SeSeLnx** [comment] 2021-05-01 12:53
Not yet, it still broken.

**Comment by SenpaiX00** [comment] 2021-05-01 13:16
So looks like we have identified the issue boils down to one or or both the "sign" and "time" headers.

**Comment by hackerin0** [comment] 2021-05-01 13:35
I confirm too it's broken. Seems like OF changed their authentication, as stated in this other issue on another OF downloader
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1078#issuecomment-830335760

**Comment by Macmasteri** [comment] 2021-05-01 13:56
> Yeah, just to confirm, it's not working for me either anymore.
> Also, I don't know if this is connected but now when I go to the OF site in the desktop Firefox browser, on the OF loading screen, I get the message: We'll try your destination again in 15 seconds" with a scroll bar across the bottom and after a few moments it goes to the site proper. Never had that before.

We'll try your destination again in 15 seconds"
Nothing new for me, sometimes that appeared during when it worked scraping.

**Comment by mwight4** [comment] 2021-05-01 21:29
They have a fix for it in the other library I don't know if the creator is following that one

**Comment by jerryhard** [comment] 2021-05-02 00:11
if some other SW work, send link ... maybe someone repair it by same way

**Comment by FightBackMode2005** [comment] 2021-05-02 05:57
It's fixed.

**Comment by dengrove** [comment] 2021-05-02 06:29
> It's fixed.

??

**Comment by SenpaiX00** [comment] 2021-05-02 08:46
> It's fixed.

What do you mean? No push to the repo in 7 days - just checked and still not fixed here

**Comment by FightBackMode2005** [comment] 2021-05-02 08:58
> > It's fixed.
> 
> What do you mean? No push to the repo in 7 days - just checked and still not fixed here

DC fixed it.  Try his scraper program.

**Comment by hackerin0** [comment] 2021-05-02 12:59
https://github.com/DIGITALCRIMINAL/OnlyFans/
This one has been fixed by the author and it's working right now

**Comment by k0rnh0li0** [comment] 2021-05-03 04:03
I've been really busy lately so I haven't had time to take a look at this yet, sorry boyz

**Comment by mw55309** [comment] 2021-05-03 15:57
Would really appreciate a fix :-D

**Comment by jonymer** [comment] 2021-05-04 04:32
> 
> 
> They have a fix for it in the other library I don't know if the creator is following that one

What other library?

**Comment by idiotabroad** [comment] 2021-05-04 08:30
https://github.com/DIGITALCRIMINAL/OnlyFans

**Comment by Eviepayne** [comment] 2021-05-04 23:15
I got some time on this anyone more familiar with onlyfans API willing to help out?

**Comment by tycho-silom** [comment] 2021-05-05 10:09
Hi all - I was fiddling with DIGITALCRIMIINAL's signing code for several hours and finally got it to work.

Created a PR with the fix. As noted, the user is gonna need to grab 2 more cookies from their browser: "auth_id" and "auth_hash", from the same place where "sess" is found, in order for the authentication to succeed. (Might be nice to put all these + the user agent string into some config file?) Also the readme should be updated if the PR is accepted

**Comment by bnsave100** [comment] 2021-05-05 11:21
@tycho-silom so ur repo is working ??

**Comment by bnsave100** [comment] 2021-05-05 11:27
> Created a PR with the fix. As noted, the user is gonna need to grab 2 more cookies from their browser: "auth_id" and "auth_hash", from the same place where "sess" is found, in order for the authentication to succeed. (Might be nice to put all these + the user agent string into some config file?) Also the readme should be updated if the PR is accepted

https://github.com/Eviepayne/onlyfans-dl this repo has config.json file

**Comment by Eviepayne** [comment] 2021-05-05 19:04
I don't see any cookie by the name of auth_hash, I assume you mean the auth_uid_{auth_id}?
I think the confusion is in the naming. Partly because this is merging digitalcriminal's code.
Should make that clear. I still can't seem to get this working. Working on merging this to my repo.

**Comment by tycho-silom** [comment] 2021-05-05 19:59
> auth_uid_

Eviepayne: are you seeing auth_uid_{auth_id} in your browser cookies? Because digitalcriminal had code for handling that which I left out because all I saw was auth_hash.

For more background: while browsing his code, it seems that OF has various methods of doing authentication, including 2-factor. I was hoping that auth_hash alone would work for most people. But let me know if that's not the case.

**Comment by tycho-silom** [comment] 2021-05-05 20:02
Also: it looks like the signing bytes have changed again and it's broken again.

Looks like OF has been changing this pretty often (every day now?) Looks like DIGITALCRIMINAL already has another fix for this:
https://github.com/DIGITALCRIMINAL/OnlyFans/commit/b4ae7e982a96842de4c2acac556f5fc37318311b

Working on integrating it...

**Comment by tycho-silom** [comment] 2021-05-05 20:39
OK this is interesting. It looks like OnlyFans is rabidly fighting the scrapers by pushing out manual updates to the servers (looks like they pushed out another update an hour ago). It seems they're willing to do this despite the negative user experience it's causing (users getting logged out and/or getting "Session locked" errors).

Might be best to just sit back for a while and see how this plays out. It's pretty entertaining though. See thread:
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1119

**Comment by Eviepayne** [comment] 2021-05-05 22:13
Yeah I saw that commit too. I already added it to my code, I'm not going to push until I get it working though. I don't get auth_hash at all. I do see fp and st they seem to be hashes. I think they may be a part of something. not sure though.

**Comment by Voldrix** [comment] 2021-05-12 21:14
I added DIGITALCRIMINAL's dynamic fix to my fork and it seems to be working for me. If it works for you guys as well, I can push it upstream. LMK [onlyfans-dl](https://github.com/Voldrix/onlyfans-dl-2)

**Comment by SenpaiX00** [comment] 2021-05-14 08:41
can you push this? I still lack a working version. 

Also, I was reading DC's Issues and it seems they went to war with the devs - has that war now ended?

**Comment by Voldrix** [comment] 2021-05-14 15:00
Pull request sent.
The OF devs keep trying to obfuscate their API by making arbitrary changes. DC was afraid the signing algorithm was set up to be fluid and change every day, but it seems now that is not the case. But most likely the devs will continue to change it manually at some random interval. So that's why the definitions are not in the script anymore, but have been pulled out and put in a separate file that the script downloads every time it runs, so that way when the definitions change no one has to update their script, he can just update the definitions file.

**Comment by HendrikKoelbel** [comment] 2021-05-19 06:31
> > Yeah it's broken for me as well.
> > Looks like all the API calls to api2/v2 require "time" and "sign" headers and if they are not set correctly you get a 401 "please refresh the page". I was able to prove this out with curl calls to api2/v2/profile/me.
> > time header looks like unix epoch time in milliseconds.
> > I'm assuming sign header is some api request signature but I haven't looked at how it is set/generated.
> 
> This is interesting. If you get any info on how it's generated, would be interesting.
> 
> Whatever the change is, it's happened today.

I found [this](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/ff0a6d6a43b75131b46381440d212e9bebe01826/apis/onlyfans/onlyfans.py#L33) on another Python project on Github. The method create_signed_headers() sounds interesting. Maybe you can do something with it.I will try to convert it to C# and implement it in my application.

Link: https://github.com/DIGITALCRIMINAL/OnlyFans/blob/ff0a6d6a43b75131b46381440d212e9bebe01826/apis/onlyfans/onlyfans.py#L33

**Comment by jedikalimero** [comment] 2021-06-02 13:57
Still no solution to this issue? :'-(

**Comment by Hekkun** [comment] 2021-07-06 20:03
I can confirm @Voldrix 's repo https://github.com/Voldrix/onlyfans-dl-2 is working.

Note that you need to follow the instructions to update the variables at the top of the script first.

Finding the sess cookie is easy but finding x_bc and user_id is more difficult. See below for those trying to figure out where it is.

![image](https://user-images.githubusercontent.com/49700980/124659936-63ef9280-de5a-11eb-90c6-92034e488380.png)

**Comment by 3ndher** [comment] 2021-09-26 20:29
Switch to firefox 🙄. chrome will always throw one of three errors like this.

**Closed** 2021-12-10 23:16 UTC
