### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by j-ktz** [k0rnh0li0/onlyfans-dl#29] opened 2021-02-03 00:08 UTC
Traceback (most recent call last):
  File "./onlyfans-dl.py", line 16, in <module>
    import requests
ImportError: No module named requests

Any idea?

**Comment by k0rnh0li0** [comment] 2021-02-03 00:10
Duplicate of #25

**Closed by k0rnh0li0** 2021-02-03 00:10 UTC
